#!/bin/bash

# Copyright (c) 2019-2020, NVIDIA CORPORATION.  All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#  * Neither the name of NVIDIA CORPORATION nor the names of its
#    contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
# OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -e

. /usr/share/debconf/confmodule

resizefs_script="/usr/lib/nvidia/resizefs/nvresizefs.sh"
desired_size=""
max_size=""
current_size=""

function query_desired_size()
{
	while true; do
		db_input critical nvresizefs/desired_size
		db_go || exit 10 # back to main menu

		# Check input size validity
		db_get nvresizefs/desired_size
		if [[ -z "${RET}" ]] || [[ "${RET}" = "0" ]]; then
			desired_size="0"
			break
		fi

		if [[ ! "${RET}" =~ ^[0-9]+$ ]]; then
			db_input high nvresizefs/invalid_size_format
			continue
		fi

		if [[ "${RET}" -lt "${current_size}" ]] || [[ "${RET}" -gt "${max_size}" ]]; then
			db_input high nvresizefs/invalid_size_range
			continue
		fi

		desired_size="${RET}"
		break
	done
}

function get_size_info()
{
	current_size="$("${resizefs_script}" -g)"
	max_size="$("${resizefs_script}" -m)"
	db_set nvresizefs/desired_size "${max_size}"
}

check_result="$("${resizefs_script}" -c)"
if [[ "${check_result}" = "false" ]]; then
	echo "nvresizefs: nvresizefs doesn't support this platform."
	exit 0
fi

get_size_info
query_desired_size

if [[ "${desired_size}" = "0" ]]; then
	"${resizefs_script}"
else
	"${resizefs_script}" -s "${desired_size}"
fi
